// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";

  interface DynamicRouter {
    "/[locale]": InferRoute<import("./src/app/[locale]/routeType").RouteType>;
  }

  interface StaticRouter {
    "/[locale]/diary/[title]/[id]": StaticRoute;
    "/[locale]/trpc-test": StaticRoute;
  }
}
