/*
 * This file is auto-generated by scripts/generate-supabase-zod.ts
 * Do not edit manually.
 */

import { z } from "zod";

export const publicEnums = {
  gender: z.enum(["male", "female"]),
} as const;

export const publicTables = {
  /** @table characters: 소설 내 등장인물 마스터 데이터 */
  characters: {
    Row: z.object({
      /** @column characters.id: 캐릭터 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid(),
      /** @column characters.novel_id: 소속 소설 ID (public.novels.id) */
      novel_id: z.uuid(),
      /** @column characters.name: 캐릭터 이름 */
      name: z.string().nullable(),
      /** @column characters.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }),
      /** @column characters.personality: 캐릭터 성격(필수) */
      personality: z.string(),
      /** @column characters.gender: 캐릭터 성별(필수): male|female */
      gender: publicEnums.gender.nullable(),
      /** @column characters.birthday: 캐릭터 생일(필수): YYYY-MM-DD */
      birthday: z.iso.date().nullable(),
      name_revealed: z.boolean(),
      descriptor: z.string().nullable(),
      first_appearance_episode_id: z.uuid().nullable(),
      first_appearance_excerpt: z.string().nullable(),
      name_revealed_in_episode_id: z.uuid().nullable(),
      name_evidence_excerpt: z.string().nullable(),
    }).strict(),
    Insert: z.object({
      /** @column characters.id: 캐릭터 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid().optional(),
      /** @column characters.novel_id: 소속 소설 ID (public.novels.id) */
      novel_id: z.uuid(),
      /** @column characters.name: 캐릭터 이름 */
      name: z.string().nullable().optional(),
      /** @column characters.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column characters.personality: 캐릭터 성격(필수) */
      personality: z.string(),
      /** @column characters.gender: 캐릭터 성별(필수): male|female */
      gender: publicEnums.gender.nullable().optional(),
      /** @column characters.birthday: 캐릭터 생일(필수): YYYY-MM-DD */
      birthday: z.iso.date().nullable().optional(),
      name_revealed: z.boolean().optional(),
      descriptor: z.string().nullable().optional(),
      first_appearance_episode_id: z.uuid().nullable().optional(),
      first_appearance_excerpt: z.string().nullable().optional(),
      name_revealed_in_episode_id: z.uuid().nullable().optional(),
      name_evidence_excerpt: z.string().nullable().optional(),
    }).strict(),
    Update: z.object({
      /** @column characters.id: 캐릭터 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid().optional(),
      /** @column characters.novel_id: 소속 소설 ID (public.novels.id) */
      novel_id: z.uuid().optional(),
      /** @column characters.name: 캐릭터 이름 */
      name: z.string().nullable().optional(),
      /** @column characters.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column characters.personality: 캐릭터 성격(필수) */
      personality: z.string().optional(),
      /** @column characters.gender: 캐릭터 성별(필수): male|female */
      gender: publicEnums.gender.nullable().optional(),
      /** @column characters.birthday: 캐릭터 생일(필수): YYYY-MM-DD */
      birthday: z.iso.date().nullable().optional(),
      name_revealed: z.boolean().optional(),
      descriptor: z.string().nullable().optional(),
      first_appearance_episode_id: z.uuid().nullable().optional(),
      first_appearance_excerpt: z.string().nullable().optional(),
      name_revealed_in_episode_id: z.uuid().nullable().optional(),
      name_evidence_excerpt: z.string().nullable().optional(),
    }).strict(),
  },
  /** @table episode_chunks: 에피소드 기반 RAG를 위한 청크/요약 및 임베딩 저장(근거 검색용) */
  episode_chunks: {
    Row: z.object({
      /** @column episode_chunks.id: 청크 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid(),
      /** @column episode_chunks.novel_id: 소속 소설 ID (public.novels.id) */
      novel_id: z.uuid(),
      /** @column episode_chunks.episode_id: 소속 에피소드 ID (public.episodes.id) */
      episode_id: z.uuid(),
      /** @column episode_chunks.episode_no: 에피소드 번호(episodes.episode_no 복제, 정렬/필터용) */
      episode_no: z.int(),
      /** @column episode_chunks.chunk_kind: 청크 종류('episode': 에피소드 요약/대표, 'fact': 사실/설정 근거, 'style': 문체 예시) */
      chunk_kind: z.string(),
      /** @column episode_chunks.chunk_index: 같은 episode_id + chunk_kind 내 0부터 시작하는 인덱스 */
      chunk_index: z.int(),
      /** @column episode_chunks.content: 임베딩 대상 텍스트(요약/근거 단락) */
      content: z.string(),
      /** @column episode_chunks.embedding: 텍스트 임베딩(pgvector) */
      embedding: z.string(),
      /** @column episode_chunks.embedding_dim: 임베딩 차원(vector_dims(embedding)과 일치) */
      embedding_dim: z.int(),
      /** @column episode_chunks.embedding_model: 임베딩 모델 식별자(예: gemini/text-embedding-004) */
      embedding_model: z.string(),
      /** @column episode_chunks.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }),
    }).strict(),
    Insert: z.object({
      /** @column episode_chunks.id: 청크 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid().optional(),
      /** @column episode_chunks.novel_id: 소속 소설 ID (public.novels.id) */
      novel_id: z.uuid(),
      /** @column episode_chunks.episode_id: 소속 에피소드 ID (public.episodes.id) */
      episode_id: z.uuid(),
      /** @column episode_chunks.episode_no: 에피소드 번호(episodes.episode_no 복제, 정렬/필터용) */
      episode_no: z.int(),
      /** @column episode_chunks.chunk_kind: 청크 종류('episode': 에피소드 요약/대표, 'fact': 사실/설정 근거, 'style': 문체 예시) */
      chunk_kind: z.string(),
      /** @column episode_chunks.chunk_index: 같은 episode_id + chunk_kind 내 0부터 시작하는 인덱스 */
      chunk_index: z.int(),
      /** @column episode_chunks.content: 임베딩 대상 텍스트(요약/근거 단락) */
      content: z.string(),
      /** @column episode_chunks.embedding: 텍스트 임베딩(pgvector) */
      embedding: z.string(),
      /** @column episode_chunks.embedding_dim: 임베딩 차원(vector_dims(embedding)과 일치) */
      embedding_dim: z.int(),
      /** @column episode_chunks.embedding_model: 임베딩 모델 식별자(예: gemini/text-embedding-004) */
      embedding_model: z.string(),
      /** @column episode_chunks.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }).optional(),
    }).strict(),
    Update: z.object({
      /** @column episode_chunks.id: 청크 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid().optional(),
      /** @column episode_chunks.novel_id: 소속 소설 ID (public.novels.id) */
      novel_id: z.uuid().optional(),
      /** @column episode_chunks.episode_id: 소속 에피소드 ID (public.episodes.id) */
      episode_id: z.uuid().optional(),
      /** @column episode_chunks.episode_no: 에피소드 번호(episodes.episode_no 복제, 정렬/필터용) */
      episode_no: z.int().optional(),
      /** @column episode_chunks.chunk_kind: 청크 종류('episode': 에피소드 요약/대표, 'fact': 사실/설정 근거, 'style': 문체 예시) */
      chunk_kind: z.string().optional(),
      /** @column episode_chunks.chunk_index: 같은 episode_id + chunk_kind 내 0부터 시작하는 인덱스 */
      chunk_index: z.int().optional(),
      /** @column episode_chunks.content: 임베딩 대상 텍스트(요약/근거 단락) */
      content: z.string().optional(),
      /** @column episode_chunks.embedding: 텍스트 임베딩(pgvector) */
      embedding: z.string().optional(),
      /** @column episode_chunks.embedding_dim: 임베딩 차원(vector_dims(embedding)과 일치) */
      embedding_dim: z.int().optional(),
      /** @column episode_chunks.embedding_model: 임베딩 모델 식별자(예: gemini/text-embedding-004) */
      embedding_model: z.string().optional(),
      /** @column episode_chunks.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }).optional(),
    }).strict(),
  },
  /** @table episodes: 소설의 회차/에피소드(챕터) 본문 */
  episodes: {
    Row: z.object({
      /** @column episodes.id: 에피소드 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid(),
      /** @column episodes.novel_id: 소속 소설 ID (public.novels.id) */
      novel_id: z.uuid(),
      /** @column episodes.episode_no: 회차 번호(정수) */
      episode_no: z.int(),
      /** @column episodes.content: 에피소드 내용(원문 텍스트) */
      content: z.string(),
      /** @column episodes.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }),
      /** @column episodes.story_time: 회차 내 사건 진행 시간(스토리 타임라인, timestamptz) */
      story_time: z.iso.datetime({ offset: true }),
    }).strict(),
    Insert: z.object({
      /** @column episodes.id: 에피소드 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid().optional(),
      /** @column episodes.novel_id: 소속 소설 ID (public.novels.id) */
      novel_id: z.uuid(),
      /** @column episodes.episode_no: 회차 번호(정수) */
      episode_no: z.int(),
      /** @column episodes.content: 에피소드 내용(원문 텍스트) */
      content: z.string(),
      /** @column episodes.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column episodes.story_time: 회차 내 사건 진행 시간(스토리 타임라인, timestamptz) */
      story_time: z.iso.datetime({ offset: true }),
    }).strict(),
    Update: z.object({
      /** @column episodes.id: 에피소드 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid().optional(),
      /** @column episodes.novel_id: 소속 소설 ID (public.novels.id) */
      novel_id: z.uuid().optional(),
      /** @column episodes.episode_no: 회차 번호(정수) */
      episode_no: z.int().optional(),
      /** @column episodes.content: 에피소드 내용(원문 텍스트) */
      content: z.string().optional(),
      /** @column episodes.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column episodes.story_time: 회차 내 사건 진행 시간(스토리 타임라인, timestamptz) */
      story_time: z.iso.datetime({ offset: true }).optional(),
    }).strict(),
  },
  /** @table locations: 소설 내 장소/배경 마스터 데이터 */
  locations: {
    Row: z.object({
      /** @column locations.id: 장소 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid(),
      /** @column locations.novel_id: 소속 소설 ID (public.novels.id) */
      novel_id: z.uuid(),
      /** @column locations.name: 장소 이름 */
      name: z.string(),
      /** @column locations.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }),
      /** @column locations.situation: 장소의 현재 상황/상태(필수) */
      situation: z.string(),
    }).strict(),
    Insert: z.object({
      /** @column locations.id: 장소 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid().optional(),
      /** @column locations.novel_id: 소속 소설 ID (public.novels.id) */
      novel_id: z.uuid(),
      /** @column locations.name: 장소 이름 */
      name: z.string(),
      /** @column locations.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column locations.situation: 장소의 현재 상황/상태(필수) */
      situation: z.string(),
    }).strict(),
    Update: z.object({
      /** @column locations.id: 장소 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid().optional(),
      /** @column locations.novel_id: 소속 소설 ID (public.novels.id) */
      novel_id: z.uuid().optional(),
      /** @column locations.name: 장소 이름 */
      name: z.string().optional(),
      /** @column locations.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column locations.situation: 장소의 현재 상황/상태(필수) */
      situation: z.string().optional(),
    }).strict(),
  },
  /** @table novels: 소설(시리즈) 메타데이터 루트 엔티티 */
  novels: {
    Row: z.object({
      /** @column novels.id: 소설 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid(),
      /** @column novels.title: 소설 제목 */
      title: z.string(),
      /** @column novels.genre: 장르(자유 텍스트) */
      genre: z.string(),
      /** @column novels.status: 소설 상태(기본값 'active') */
      status: z.string(),
      /** @column novels.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }),
      /** @column novels.story_bible: 소설 성경/스토리 바이블(Markdown 텍스트) */
      story_bible: z.string(),
    }).strict(),
    Insert: z.object({
      /** @column novels.id: 소설 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid().optional(),
      /** @column novels.title: 소설 제목 */
      title: z.string(),
      /** @column novels.genre: 장르(자유 텍스트) */
      genre: z.string(),
      /** @column novels.status: 소설 상태(기본값 'active') */
      status: z.string().optional(),
      /** @column novels.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column novels.story_bible: 소설 성경/스토리 바이블(Markdown 텍스트) */
      story_bible: z.string().optional(),
    }).strict(),
    Update: z.object({
      /** @column novels.id: 소설 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid().optional(),
      /** @column novels.title: 소설 제목 */
      title: z.string().optional(),
      /** @column novels.genre: 장르(자유 텍스트) */
      genre: z.string().optional(),
      /** @column novels.status: 소설 상태(기본값 'active') */
      status: z.string().optional(),
      /** @column novels.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column novels.story_bible: 소설 성경/스토리 바이블(Markdown 텍스트) */
      story_bible: z.string().optional(),
    }).strict(),
  },
  /** @table plot_seed_characters: 플롯 시드 ↔ 캐릭터 N:M 연결(조인 테이블) */
  plot_seed_characters: {
    Row: z.object({
      /** @column plot_seed_characters.plot_seed_id: 플롯 시드 ID (public.plot_seeds.id) */
      plot_seed_id: z.uuid(),
      /** @column plot_seed_characters.character_id: 캐릭터 ID (public.characters.id) */
      character_id: z.uuid(),
      /** @column plot_seed_characters.created_at: 연결 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }),
    }).strict(),
    Insert: z.object({
      /** @column plot_seed_characters.plot_seed_id: 플롯 시드 ID (public.plot_seeds.id) */
      plot_seed_id: z.uuid(),
      /** @column plot_seed_characters.character_id: 캐릭터 ID (public.characters.id) */
      character_id: z.uuid(),
      /** @column plot_seed_characters.created_at: 연결 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }).optional(),
    }).strict(),
    Update: z.object({
      /** @column plot_seed_characters.plot_seed_id: 플롯 시드 ID (public.plot_seeds.id) */
      plot_seed_id: z.uuid().optional(),
      /** @column plot_seed_characters.character_id: 캐릭터 ID (public.characters.id) */
      character_id: z.uuid().optional(),
      /** @column plot_seed_characters.created_at: 연결 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }).optional(),
    }).strict(),
  },
  /** @table plot_seed_locations: 플롯 시드 ↔ 장소 N:M 연결(조인 테이블) */
  plot_seed_locations: {
    Row: z.object({
      /** @column plot_seed_locations.plot_seed_id: 플롯 시드 ID (public.plot_seeds.id) */
      plot_seed_id: z.uuid(),
      /** @column plot_seed_locations.location_id: 장소 ID (public.locations.id) */
      location_id: z.uuid(),
      /** @column plot_seed_locations.created_at: 연결 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }),
    }).strict(),
    Insert: z.object({
      /** @column plot_seed_locations.plot_seed_id: 플롯 시드 ID (public.plot_seeds.id) */
      plot_seed_id: z.uuid(),
      /** @column plot_seed_locations.location_id: 장소 ID (public.locations.id) */
      location_id: z.uuid(),
      /** @column plot_seed_locations.created_at: 연결 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }).optional(),
    }).strict(),
    Update: z.object({
      /** @column plot_seed_locations.plot_seed_id: 플롯 시드 ID (public.plot_seeds.id) */
      plot_seed_id: z.uuid().optional(),
      /** @column plot_seed_locations.location_id: 장소 ID (public.locations.id) */
      location_id: z.uuid().optional(),
      /** @column plot_seed_locations.created_at: 연결 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }).optional(),
    }).strict(),
  },
  /** @table plot_seeds: 떡밥/플롯 시드(미해결 과제, 사건의 씨앗) 관리 */
  plot_seeds: {
    Row: z.object({
      /** @column plot_seeds.id: 플롯 시드 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid(),
      /** @column plot_seeds.novel_id: 소속 소설 ID (public.novels.id) */
      novel_id: z.uuid(),
      /** @column plot_seeds.title: 떡밥 제목/요약 */
      title: z.string(),
      /** @column plot_seeds.detail: 떡밥 상세 설명 */
      detail: z.string(),
      /** @column plot_seeds.status: 떡밥 상태(기본값 'open') */
      status: z.string(),
      /** @column plot_seeds.introduced_in_episode_id: 등장 에피소드 ID (public.episodes.id, Nullable) */
      introduced_in_episode_id: z.uuid().nullable(),
      /** @column plot_seeds.resolved_in_episode_id: 해결 에피소드 ID (public.episodes.id, Nullable) */
      resolved_in_episode_id: z.uuid().nullable(),
      /** @column plot_seeds.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }),
    }).strict(),
    Insert: z.object({
      /** @column plot_seeds.id: 플롯 시드 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid().optional(),
      /** @column plot_seeds.novel_id: 소속 소설 ID (public.novels.id) */
      novel_id: z.uuid(),
      /** @column plot_seeds.title: 떡밥 제목/요약 */
      title: z.string(),
      /** @column plot_seeds.detail: 떡밥 상세 설명 */
      detail: z.string(),
      /** @column plot_seeds.status: 떡밥 상태(기본값 'open') */
      status: z.string().optional(),
      /** @column plot_seeds.introduced_in_episode_id: 등장 에피소드 ID (public.episodes.id, Nullable) */
      introduced_in_episode_id: z.uuid().nullable().optional(),
      /** @column plot_seeds.resolved_in_episode_id: 해결 에피소드 ID (public.episodes.id, Nullable) */
      resolved_in_episode_id: z.uuid().nullable().optional(),
      /** @column plot_seeds.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }).optional(),
    }).strict(),
    Update: z.object({
      /** @column plot_seeds.id: 플롯 시드 ID (UUID, 기본값 gen_random_uuid()) */
      id: z.uuid().optional(),
      /** @column plot_seeds.novel_id: 소속 소설 ID (public.novels.id) */
      novel_id: z.uuid().optional(),
      /** @column plot_seeds.title: 떡밥 제목/요약 */
      title: z.string().optional(),
      /** @column plot_seeds.detail: 떡밥 상세 설명 */
      detail: z.string().optional(),
      /** @column plot_seeds.status: 떡밥 상태(기본값 'open') */
      status: z.string().optional(),
      /** @column plot_seeds.introduced_in_episode_id: 등장 에피소드 ID (public.episodes.id, Nullable) */
      introduced_in_episode_id: z.uuid().nullable().optional(),
      /** @column plot_seeds.resolved_in_episode_id: 해결 에피소드 ID (public.episodes.id, Nullable) */
      resolved_in_episode_id: z.uuid().nullable().optional(),
      /** @column plot_seeds.created_at: 생성 시각(기본값 now()) */
      created_at: z.iso.datetime({ offset: true }).optional(),
    }).strict(),
  },
} as const;

export const SupabaseZod = {
  public: {
    Enums: publicEnums,
    Tables: publicTables,
  },
} as const;