/*
 * This file is auto-generated by scripts/generate-supabase-zod.ts
 * Do not edit manually.
 */

import { z } from "zod";

export const publicEnums = {
} as const;

export const publicTables = {
  characters: {
    Row: z.object({
      /** @column characters.id: 캐릭터 고유 ID (NanoID) */
      id: z.string().nanoid(),
      /** @column characters.novel_id: 소설 ID */
      novel_id: z.string(),
      /** @column characters.name: 캐릭터 이름 */
      name: z.string(),
      /** @column characters.traits: 캐릭터 특징 (선택 사항) */
      traits: z.string().nullable(),
      /** @column characters.personality: 캐릭터 성격 설명 (선택 사항) */
      personality: z.string().nullable(),
      /** @column characters.description: 캐릭터 상세 설명 (선택 사항) */
      description: z.string().nullable(),
      /** @column characters.created_at: 생성 시간 */
      created_at: z.iso.datetime({ offset: true }),
      /** @column characters.updated_at: 마지막 수정 시간 */
      updated_at: z.iso.datetime({ offset: true }),
    }).strict(),
    Insert: z.object({
      /** @column characters.id: 캐릭터 고유 ID (NanoID) */
      id: z.string().nanoid().optional(),
      /** @column characters.novel_id: 소설 ID */
      novel_id: z.string(),
      /** @column characters.name: 캐릭터 이름 */
      name: z.string(),
      /** @column characters.traits: 캐릭터 특징 (선택 사항) */
      traits: z.string().nullable().optional(),
      /** @column characters.personality: 캐릭터 성격 설명 (선택 사항) */
      personality: z.string().nullable().optional(),
      /** @column characters.description: 캐릭터 상세 설명 (선택 사항) */
      description: z.string().nullable().optional(),
      /** @column characters.created_at: 생성 시간 */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column characters.updated_at: 마지막 수정 시간 */
      updated_at: z.iso.datetime({ offset: true }).optional(),
    }).strict(),
    Update: z.object({
      /** @column characters.id: 캐릭터 고유 ID (NanoID) */
      id: z.string().nanoid().optional(),
      /** @column characters.novel_id: 소설 ID */
      novel_id: z.string().optional(),
      /** @column characters.name: 캐릭터 이름 */
      name: z.string().optional(),
      /** @column characters.traits: 캐릭터 특징 (선택 사항) */
      traits: z.string().nullable().optional(),
      /** @column characters.personality: 캐릭터 성격 설명 (선택 사항) */
      personality: z.string().nullable().optional(),
      /** @column characters.description: 캐릭터 상세 설명 (선택 사항) */
      description: z.string().nullable().optional(),
      /** @column characters.created_at: 생성 시간 */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column characters.updated_at: 마지막 수정 시간 */
      updated_at: z.iso.datetime({ offset: true }).optional(),
    }).strict(),
  },
  episode_characters: {
    Row: z.object({
      /** @column episode_characters.id: 조인 레코드 고유 ID (NanoID) */
      id: z.string().nanoid(),
      /** @column episode_characters.episode_id: 에피소드 ID */
      episode_id: z.string(),
      /** @column episode_characters.character_id: 캐릭터 ID */
      character_id: z.string(),
      /** @column episode_characters.created_at: 생성 시간 */
      created_at: z.iso.datetime({ offset: true }),
      /** @column episode_characters.updated_at: 마지막 수정 시간 */
      updated_at: z.iso.datetime({ offset: true }).nullable(),
    }).strict(),
    Insert: z.object({
      /** @column episode_characters.id: 조인 레코드 고유 ID (NanoID) */
      id: z.string().nanoid().optional(),
      /** @column episode_characters.episode_id: 에피소드 ID */
      episode_id: z.string(),
      /** @column episode_characters.character_id: 캐릭터 ID */
      character_id: z.string(),
      /** @column episode_characters.created_at: 생성 시간 */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column episode_characters.updated_at: 마지막 수정 시간 */
      updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
    }).strict(),
    Update: z.object({
      /** @column episode_characters.id: 조인 레코드 고유 ID (NanoID) */
      id: z.string().nanoid().optional(),
      /** @column episode_characters.episode_id: 에피소드 ID */
      episode_id: z.string().optional(),
      /** @column episode_characters.character_id: 캐릭터 ID */
      character_id: z.string().optional(),
      /** @column episode_characters.created_at: 생성 시간 */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column episode_characters.updated_at: 마지막 수정 시간 */
      updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
    }).strict(),
  },
  episode_locations: {
    Row: z.object({
      /** @column episode_locations.id: 조인 레코드 고유 ID (NanoID) */
      id: z.string().nanoid(),
      /** @column episode_locations.episode_id: 에피소드 ID */
      episode_id: z.string(),
      /** @column episode_locations.location_id: 장소 ID */
      location_id: z.string(),
      /** @column episode_locations.created_at: 생성 시간 */
      created_at: z.iso.datetime({ offset: true }),
      /** @column episode_locations.updated_at: 마지막 수정 시간 */
      updated_at: z.iso.datetime({ offset: true }).nullable(),
    }).strict(),
    Insert: z.object({
      /** @column episode_locations.id: 조인 레코드 고유 ID (NanoID) */
      id: z.string().nanoid().optional(),
      /** @column episode_locations.episode_id: 에피소드 ID */
      episode_id: z.string(),
      /** @column episode_locations.location_id: 장소 ID */
      location_id: z.string(),
      /** @column episode_locations.created_at: 생성 시간 */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column episode_locations.updated_at: 마지막 수정 시간 */
      updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
    }).strict(),
    Update: z.object({
      /** @column episode_locations.id: 조인 레코드 고유 ID (NanoID) */
      id: z.string().nanoid().optional(),
      /** @column episode_locations.episode_id: 에피소드 ID */
      episode_id: z.string().optional(),
      /** @column episode_locations.location_id: 장소 ID */
      location_id: z.string().optional(),
      /** @column episode_locations.created_at: 생성 시간 */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column episode_locations.updated_at: 마지막 수정 시간 */
      updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
    }).strict(),
  },
  episodes: {
    Row: z.object({
      /** @column episodes.id: 에피소드 고유 ID (NanoID) */
      id: z.string().nanoid(),
      /** @column episodes.novel_id: 소설 ID */
      novel_id: z.string(),
      /** @column episodes.episode_number: 에피소드 번호 (1부터 시작) */
      episode_number: z.int(),
      /** @column episodes.body: 에피소드 본문 */
      body: z.string(),
      /** @column episodes.embedding: 에피소드 본문의 임베딩 벡터 (JSON 배열 형식, 선택 사항) */
      embedding: z.unknown().nullable(),
      /** @column episodes.embedding_model: 임베딩 생성에 사용된 모델 식별자 */
      embedding_model: z.string().nullable(),
      /** @column episodes.created_at: 생성 시간 */
      created_at: z.iso.datetime({ offset: true }),
      /** @column episodes.updated_at: 마지막 수정 시간 */
      updated_at: z.iso.datetime({ offset: true }),
    }).strict(),
    Insert: z.object({
      /** @column episodes.id: 에피소드 고유 ID (NanoID) */
      id: z.string().nanoid().optional(),
      /** @column episodes.novel_id: 소설 ID */
      novel_id: z.string(),
      /** @column episodes.episode_number: 에피소드 번호 (1부터 시작) */
      episode_number: z.int(),
      /** @column episodes.body: 에피소드 본문 */
      body: z.string(),
      /** @column episodes.embedding: 에피소드 본문의 임베딩 벡터 (JSON 배열 형식, 선택 사항) */
      embedding: z.unknown().nullable().optional(),
      /** @column episodes.embedding_model: 임베딩 생성에 사용된 모델 식별자 */
      embedding_model: z.string().nullable().optional(),
      /** @column episodes.created_at: 생성 시간 */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column episodes.updated_at: 마지막 수정 시간 */
      updated_at: z.iso.datetime({ offset: true }).optional(),
    }).strict(),
    Update: z.object({
      /** @column episodes.id: 에피소드 고유 ID (NanoID) */
      id: z.string().nanoid().optional(),
      /** @column episodes.novel_id: 소설 ID */
      novel_id: z.string().optional(),
      /** @column episodes.episode_number: 에피소드 번호 (1부터 시작) */
      episode_number: z.int().optional(),
      /** @column episodes.body: 에피소드 본문 */
      body: z.string().optional(),
      /** @column episodes.embedding: 에피소드 본문의 임베딩 벡터 (JSON 배열 형식, 선택 사항) */
      embedding: z.unknown().nullable().optional(),
      /** @column episodes.embedding_model: 임베딩 생성에 사용된 모델 식별자 */
      embedding_model: z.string().nullable().optional(),
      /** @column episodes.created_at: 생성 시간 */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column episodes.updated_at: 마지막 수정 시간 */
      updated_at: z.iso.datetime({ offset: true }).optional(),
    }).strict(),
  },
  locations: {
    Row: z.object({
      /** @column locations.id: 장소 고유 ID (NanoID) */
      id: z.string().nanoid(),
      /** @column locations.novel_id: 소설 ID */
      novel_id: z.string(),
      /** @column locations.name: 장소 이름 */
      name: z.string(),
      /** @column locations.description: 장소 설명 (선택 사항) */
      description: z.string().nullable(),
      /** @column locations.created_at: 생성 시간 */
      created_at: z.iso.datetime({ offset: true }),
      /** @column locations.updated_at: 마지막 수정 시간 */
      updated_at: z.iso.datetime({ offset: true }),
    }).strict(),
    Insert: z.object({
      /** @column locations.id: 장소 고유 ID (NanoID) */
      id: z.string().nanoid().optional(),
      /** @column locations.novel_id: 소설 ID */
      novel_id: z.string(),
      /** @column locations.name: 장소 이름 */
      name: z.string(),
      /** @column locations.description: 장소 설명 (선택 사항) */
      description: z.string().nullable().optional(),
      /** @column locations.created_at: 생성 시간 */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column locations.updated_at: 마지막 수정 시간 */
      updated_at: z.iso.datetime({ offset: true }).optional(),
    }).strict(),
    Update: z.object({
      /** @column locations.id: 장소 고유 ID (NanoID) */
      id: z.string().nanoid().optional(),
      /** @column locations.novel_id: 소설 ID */
      novel_id: z.string().optional(),
      /** @column locations.name: 장소 이름 */
      name: z.string().optional(),
      /** @column locations.description: 장소 설명 (선택 사항) */
      description: z.string().nullable().optional(),
      /** @column locations.created_at: 생성 시간 */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column locations.updated_at: 마지막 수정 시간 */
      updated_at: z.iso.datetime({ offset: true }).optional(),
    }).strict(),
  },
  novels: {
    Row: z.object({
      /** @column novels.id: 소설 고유 ID (nanoid) */
      id: z.string().nanoid(),
      /** @column novels.title: 소설 제목 */
      title: z.string(),
      /** @column novels.genre: 장르(자유 텍스트) */
      genre: z.string(),
      /** @column novels.status: 소설 상태(기본값 'active') */
      status: z.string(),
      /** @column novels.created_at: 소설 생성 시각 */
      created_at: z.iso.datetime({ offset: true }),
      /** @column novels.story_bible: 소설 세계관, 설정, 톤앤매너 등 작품 전반의 바이블  (Markdown) */
      story_bible: z.string(),
      /** @column novels.append_prompt: Writer Agent 실행 시 추가로 전달할 프롬프트 (Markdown) */
      append_prompt: z.string().nullable(),
      /** @column novels.updated_at: 소설 정보 마지막 수정 시각 */
      updated_at: z.iso.datetime({ offset: true }).nullable(),
      /** @column novels.initial_plot_seeds: 초기 플롯 시드  (Markdown) */
      initial_plot_seeds: z.string().nullable(),
      /** @column novels.plot_seeds_resolved: 초기 플롯 시드가 모두 회수되었는지 여부 */
      plot_seeds_resolved: z.boolean().nullable(),
    }).strict(),
    Insert: z.object({
      /** @column novels.id: 소설 고유 ID (nanoid) */
      id: z.string().nanoid().optional(),
      /** @column novels.title: 소설 제목 */
      title: z.string(),
      /** @column novels.genre: 장르(자유 텍스트) */
      genre: z.string(),
      /** @column novels.status: 소설 상태(기본값 'active') */
      status: z.string().optional(),
      /** @column novels.created_at: 소설 생성 시각 */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column novels.story_bible: 소설 세계관, 설정, 톤앤매너 등 작품 전반의 바이블  (Markdown) */
      story_bible: z.string().optional(),
      /** @column novels.append_prompt: Writer Agent 실행 시 추가로 전달할 프롬프트 (Markdown) */
      append_prompt: z.string().nullable().optional(),
      /** @column novels.updated_at: 소설 정보 마지막 수정 시각 */
      updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
      /** @column novels.initial_plot_seeds: 초기 플롯 시드  (Markdown) */
      initial_plot_seeds: z.string().nullable().optional(),
      /** @column novels.plot_seeds_resolved: 초기 플롯 시드가 모두 회수되었는지 여부 */
      plot_seeds_resolved: z.boolean().nullable().optional(),
    }).strict(),
    Update: z.object({
      /** @column novels.id: 소설 고유 ID (nanoid) */
      id: z.string().nanoid().optional(),
      /** @column novels.title: 소설 제목 */
      title: z.string().optional(),
      /** @column novels.genre: 장르(자유 텍스트) */
      genre: z.string().optional(),
      /** @column novels.status: 소설 상태(기본값 'active') */
      status: z.string().optional(),
      /** @column novels.created_at: 소설 생성 시각 */
      created_at: z.iso.datetime({ offset: true }).optional(),
      /** @column novels.story_bible: 소설 세계관, 설정, 톤앤매너 등 작품 전반의 바이블  (Markdown) */
      story_bible: z.string().optional(),
      /** @column novels.append_prompt: Writer Agent 실행 시 추가로 전달할 프롬프트 (Markdown) */
      append_prompt: z.string().nullable().optional(),
      /** @column novels.updated_at: 소설 정보 마지막 수정 시각 */
      updated_at: z.iso.datetime({ offset: true }).nullable().optional(),
      /** @column novels.initial_plot_seeds: 초기 플롯 시드  (Markdown) */
      initial_plot_seeds: z.string().nullable().optional(),
      /** @column novels.plot_seeds_resolved: 초기 플롯 시드가 모두 회수되었는지 여부 */
      plot_seeds_resolved: z.boolean().nullable().optional(),
    }).strict(),
  },
} as const;

export const SupabaseZod = {
  public: {
    Enums: publicEnums,
    Tables: publicTables,
  },
} as const;